service: nft-marketplace
useDotenv: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000
  customDomain:
    apiType: rest
    autoDomain: true
    basePath: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: 
    domainName: bxpp.io
    endpointType: 'edge'
    hostedZoneId:  
    securityPolicy: tls_1_2

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  apiName: marketplace-service
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    IPFS_HOST: ${env:REACT_APP_HOST}
    IPFS_PROTOCOL: ${env:REACT_APP_PROTOCOL}
    IPFS_PORT: ${env:REACT_APP_PORT}
    APIETHERSCAN: ${env:APIETHERSCAN}
    IPFS_INFURA_PROJECT_ID: ${env:REACT_APP_PROJECT_ID}
    IPFS_INFURA_SECRET: ${env:REACT_APP_PROJECT_SECRET}

functions:
  app: 
    handler: handler.app
    events:
      - http:
          method: get
          path: app
          cors: true
  mint:
    handler: handler.mint
    events:
      - http:
          method: post
          path: mint
          cors: true

  addItem:
    handler: handler.addItem
    events:
      - http:
          method: post
          path: addItem
          cors: true

  deleteItem:
    handler: handler.deleteItem
    events:
      - http:
          method: post
          path: deleteItem
          cors: true

  updateItem:
    handler: handler.updateItem
    events:
      - http:
          method: post
          path: updateItem
          cors: true

  tokens: 
    handler: handler.token
    events:
      - http:
          method: post
          path: token
          cors: true

  token: 
    handler: handler.token
    events:
      - http:
          method: post
          path: token/{id}
          cors: true
  
  contracts: 
    handler: handler.contract
    events:
      - http:
          method: get
          path: contract
          cors: true

  contract: 
    handler: handler.contract
    events:
      - http:
          method: get
          path: contract/{id}
          cors: true

  addContract:
    handler: handler.addContract
    events:
      - http:
          method: post
          path: addContract
          cors: true

  ethusd:
    handler: handler.ethusd
    events:
      - http:
          method: get
          path: ethusd
          cors: true
